# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 65bc2399971a989fb3bdceb8e0380e2e2e13513f43f7156dbcf8ce62109b31bae94206295bc8e6b1f527bb17d0ff1190b57e53b2308e044e2bfa3e6f0828b6a7

test:
  secret_key_base: fd39b620a636fcf7c0c52ece25e125cea31b55081baa9a02e0b80b5e9de98c867c42b197f7968ff697945d631614bd8bb6021c668630e60421957586ade1f687

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
